{% set name = "torch-pme" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/torch_pme/torch_pme-{{ version }}.tar.gz
  sha256: 8ee9b387e6830c1a6d982873a49abcecdb7c3038a41d927a80784fb1fecb2385

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >={{ python_min }}
    - pytorch >=2.3

test:
  imports:
    - torchpme
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://lab-cosmo.github.io/torch-pme
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Particle-mesh based calculations of long-range interactions in PyTorch
  description: |
    torch-pme enables efficient, auto-differentiable computation of long-range
    interactions in PyTorch. Auto-differentiation is supported for particle positions,
    charges, and cell parameters, allowing not only the automatic computation of forces
    but also enabling general applications in machine learning tasks.
  doc_url: https://lab-cosmo.github.io/torch-pme
  dev_url: https://github.com/lab-cosmo/torch-pme
  doc_source_url: https://github.com/lab-cosmo/torch-pme/blob/main/README.rst

extra:
  recipe-maintainers:
    - PicoCentauri
    - Luthaf
